id = "theme-ember"
name = "Ember"
version = "0.5.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Ember theme for Zed"
repository = "https://github.com/blaqat/zed-themes/ember"
