id = "tomorrow"
name = "Tomorrow"
version = "0.5.0"
schema_version = 1
authors = ["blaqat <aidengreenj@gmail.com>"]
description = "
based on chriskempson's ["Tomorrow Theme"](<https://github.com/chriskempson/tomorrow-theme?tab=readme-ov-file>)  as well as some port/forks: (VSCode's "[Tomorrow Night Blue](<https://arc.net/l/quote/nbuipqzx\>\)", [mdBook](<https://rust-lang.github.io/mdBook/for_developers/preprocessors.html\>\)'s "Coal", and [rusty.nvim](<https://github.com/namrabtw/rusty.nvim?tab=readme-ov-file>))
"
repository = "https://github.com/blaqat/zed-themes/tomorrow"
